// ============================================================
// NEXORA — Product Seed Data
// ============================================================

import type { Product } from '@/types';

export const SEED_PRODUCTS: Omit<Product, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Void Oversized Tee',
    slug: 'void-oversized-tee',
    description: 'The Void Oversized Tee is our signature black essential. Cut from 280gsm heavyweight organic cotton, it features a relaxed drop-shoulder silhouette, reinforced neckline, and a subtle embroidered NEXORA mark. Built for all-day comfort with a structured drape that holds its shape.',
    price: 899,
    compareAtPrice: 1199,
    category: 'men',
    collection: 'core',
    images: ['/assets/products/men-black-tee.jpg'],
    sizes: [
      { size: 'S', stock: 15, lowStockThreshold: 5 },
      { size: 'M', stock: 8, lowStockThreshold: 5 },
      { size: 'L', stock: 22, lowStockThreshold: 5 },
      { size: 'XL', stock: 18, lowStockThreshold: 5 },
    ],
    colors: ['black'],
    materials: ['100% Organic Cotton'],
    sku: 'NXR-M-001',
    tags: ['oversized', 'essential', 'black'],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isLimitedDrop: false,
    rating: 4.9,
    reviewCount: 127,
    seoTitle: 'Void Oversized Tee | NEXORA',
    seoDescription: 'Our signature black oversized t-shirt. 280gsm organic cotton. Built different.',
  },
  {
    name: 'Sage Essential Tee',
    slug: 'sage-essential-tee',
    description: 'The Sage Essential Tee brings muted earth tones to your summer wardrobe. Crafted from premium Pima cotton with a garment-washed finish for ultimate softness. The relaxed fit and dropped shoulders create an effortlessly modern silhouette.',
    price: 799,
    category: 'men',
    collection: 'summer-2024',
    images: ['/assets/products/men-sage-tee.jpg'],
    sizes: [
      { size: 'S', stock: 12, lowStockThreshold: 5 },
      { size: 'M', stock: 20, lowStockThreshold: 5 },
      { size: 'L', stock: 15, lowStockThreshold: 5 },
      { size: 'XL', stock: 10, lowStockThreshold: 5 },
      { size: 'XXL', stock: 6, lowStockThreshold: 5 },
    ],
    colors: ['sage'],
    materials: ['Premium Cotton Blend'],
    sku: 'NXR-M-002',
    tags: ['sage', 'summer', 'essential'],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isLimitedDrop: false,
    rating: 4.7,
    reviewCount: 84,
    seoTitle: 'Sage Essential Tee | NEXORA',
    seoDescription: 'Premium sage green t-shirt. Pima cotton comfort. Summer essential.',
  },
  {
    name: 'Bone Classic Tee',
    slug: 'bone-classic-tee',
    description: 'The Bone Classic Tee in warm cream offers timeless versatility. Made from Egyptian cotton with a smooth hand-feel, this piece features a classic crew neck and tailored fit that works as a standalone statement or a layering foundation.',
    price: 849,
    compareAtPrice: 999,
    category: 'men',
    collection: 'core',
    images: ['/assets/products/men-cream-tee.jpg'],
    sizes: [
      { size: 'S', stock: 18, lowStockThreshold: 5 },
      { size: 'M', stock: 25, lowStockThreshold: 5 },
      { size: 'L', stock: 20, lowStockThreshold: 5 },
      { size: 'XL', stock: 14, lowStockThreshold: 5 },
    ],
    colors: ['cream'],
    materials: ['Egyptian Cotton'],
    sku: 'NXR-M-003',
    tags: ['cream', 'classic', 'essential'],
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isLimitedDrop: false,
    rating: 4.8,
    reviewCount: 156,
    seoTitle: 'Bone Classic Tee | NEXORA',
    seoDescription: 'Egyptian cotton cream t-shirt. Timeless essential. Built different.',
  },
  {
    name: 'Deep Navy Oversized Tee',
    slug: 'deep-navy-oversized-tee',
    description: 'The Deep Navy Oversized Tee combines maritime heritage with modern streetwear. Cut from 300gsm heavyweight cotton in a rich navy tone, featuring a boxy silhouette, wide sleeves, and our signature side-slit hem for enhanced mobility.',
    price: 949,
    category: 'men',
    collection: 'summer-2024',
    images: ['/assets/products/men-navy-tee.jpg'],
    sizes: [
      { size: 'S', stock: 9, lowStockThreshold: 5 },
      { size: 'M', stock: 14, lowStockThreshold: 5 },
      { size: 'L', stock: 11, lowStockThreshold: 5 },
      { size: 'XL', stock: 7, lowStockThreshold: 5 },
    ],
    colors: ['navy'],
    materials: ['100% Organic Cotton'],
    sku: 'NXR-M-004',
    tags: ['navy', 'oversized', 'heavyweight'],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isLimitedDrop: true,
    rating: 4.6,
    reviewCount: 62,
    seoTitle: 'Deep Navy Oversized Tee | NEXORA',
    seoDescription: 'Heavyweight navy oversized t-shirt. Limited summer drop.',
  },
  {
    name: 'Graphite Heather Tee',
    slug: 'graphite-heather-tee',
    description: 'The Graphite Heather Tee offers a sophisticated take on casual basics. The heathered cotton-poly blend creates visual depth while maintaining breathability. Features a slim modern fit with a clean neckline and double-stitched hem.',
    price: 699,
    category: 'men',
    collection: 'core',
    images: ['/assets/products/men-gray-tee.jpg'],
    sizes: [
      { size: 'S', stock: 20, lowStockThreshold: 5 },
      { size: 'M', stock: 18, lowStockThreshold: 5 },
      { size: 'L', stock: 16, lowStockThreshold: 5 },
      { size: 'XL', stock: 12, lowStockThreshold: 5 },
    ],
    colors: ['gray'],
    materials: ['Premium Cotton Blend'],
    sku: 'NXR-M-005',
    tags: ['gray', 'heather', 'basic'],
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isLimitedDrop: false,
    rating: 4.5,
    reviewCount: 93,
    seoTitle: 'Graphite Heather Tee | NEXORA',
    seoDescription: 'Premium heather gray t-shirt. Modern essential fit.',
  },
  {
    name: 'Ivory Crop Tee',
    slug: 'ivory-crop-tee',
    description: 'The Ivory Crop Tee redefines summer minimalism. Cut from ultra-soft organic cotton jersey, this cropped silhouette hits at the natural waist. Features a relaxed crew neck and slightly extended sleeves for a contemporary proportion.',
    price: 749,
    compareAtPrice: 899,
    category: 'women',
    collection: 'summer-2024',
    images: ['/assets/products/women-white-tee.jpg'],
    sizes: [
      { size: 'S', stock: 14, lowStockThreshold: 5 },
      { size: 'M', stock: 10, lowStockThreshold: 5 },
      { size: 'L', stock: 8, lowStockThreshold: 5 },
      { size: 'XL', stock: 5, lowStockThreshold: 5 },
    ],
    colors: ['white'],
    materials: ['100% Organic Cotton'],
    sku: 'NXR-W-001',
    tags: ['crop', 'white', 'summer'],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isLimitedDrop: false,
    rating: 4.8,
    reviewCount: 112,
    seoTitle: 'Ivory Crop Tee | NEXORA Women',
    seoDescription: 'Premium white crop t-shirt. Organic cotton. Summer essential.',
  },
  {
    name: 'Terracotta Relaxed Tee',
    slug: 'terracotta-relaxed-tee',
    description: 'The Terracotta Relaxed Tee draws inspiration from desert landscapes. This earthy tone is achieved through natural dyeing processes on premium cotton. The oversized relaxed fit drapes beautifully, with rolled sleeve cuffs and a raw-edge hem.',
    price: 849,
    category: 'women',
    collection: 'summer-2024',
    images: ['/assets/products/women-terracotta-tee.jpg'],
    sizes: [
      { size: 'S', stock: 11, lowStockThreshold: 5 },
      { size: 'M', stock: 16, lowStockThreshold: 5 },
      { size: 'L', stock: 13, lowStockThreshold: 5 },
      { size: 'XL', stock: 9, lowStockThreshold: 5 },
    ],
    colors: ['terracotta'],
    materials: ['Premium Cotton Blend'],
    sku: 'NXR-W-002',
    tags: ['terracotta', 'relaxed', 'earth-tone'],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isLimitedDrop: true,
    rating: 4.7,
    reviewCount: 78,
    seoTitle: 'Terracotta Relaxed Tee | NEXORA Women',
    seoDescription: 'Limited terracotta t-shirt. Natural dyed cotton. Desert inspired.',
  },
  {
    name: 'Onyx Fitted Tee',
    slug: 'onyx-fitted-tee',
    description: 'The Onyx Fitted Tee is the ultimate black essential for women. Crafted from a sculpting cotton-modal blend that hugs the body without constriction. Features a flattering scoop neckline, cap sleeves, and precision stitching throughout.',
    price: 799,
    category: 'women',
    collection: 'core',
    images: ['/assets/products/women-black-tee.jpg'],
    sizes: [
      { size: 'S', stock: 22, lowStockThreshold: 5 },
      { size: 'M', stock: 19, lowStockThreshold: 5 },
      { size: 'L', stock: 15, lowStockThreshold: 5 },
      { size: 'XL', stock: 11, lowStockThreshold: 5 },
    ],
    colors: ['black'],
    materials: ['Bamboo Cotton'],
    sku: 'NXR-W-003',
    tags: ['black', 'fitted', 'essential'],
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isLimitedDrop: false,
    rating: 4.9,
    reviewCount: 203,
    seoTitle: 'Onyx Fitted Tee | NEXORA Women',
    seoDescription: 'Sculpting black fitted t-shirt. Bamboo cotton blend. Core essential.',
  },
  {
    name: 'Rose Dust Oversized Tee',
    slug: 'rose-dust-oversized-tee',
    description: 'The Rose Dust Oversized Tee softens the silhouette in a dreamy muted pink. Cut from premium cotton with a brushed interior for cloud-like softness. The exaggerated drop shoulders and elongated body create a borrowed-from-him aesthetic.',
    price: 899,
    compareAtPrice: 1099,
    category: 'women',
    collection: 'summer-2024',
    images: ['/assets/products/women-rose-tee.jpg'],
    sizes: [
      { size: 'S', stock: 7, lowStockThreshold: 5 },
      { size: 'M', stock: 12, lowStockThreshold: 5 },
      { size: 'L', stock: 9, lowStockThreshold: 5 },
      { size: 'XL', stock: 6, lowStockThreshold: 5 },
    ],
    colors: ['pink'],
    materials: ['100% Organic Cotton'],
    sku: 'NXR-W-004',
    tags: ['pink', 'oversized', 'soft'],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isLimitedDrop: true,
    rating: 4.6,
    reviewCount: 54,
    seoTitle: 'Rose Dust Oversized Tee | NEXORA Women',
    seoDescription: 'Limited rose dust oversized t-shirt. Brushed organic cotton.',
  },
  {
    name: 'Sand Relaxed Tee',
    slug: 'sand-relaxed-tee',
    description: 'The Sand Relaxed Tee captures the essence of summer warmth. In a versatile sand beige tone, this piece features a relaxed boxy fit, wide neckline, and side vents for movement. Made from lightweight linen-cotton blend perfect for hot days.',
    price: 749,
    category: 'women',
    collection: 'core',
    images: ['/assets/products/women-sand-tee.jpg'],
    sizes: [
      { size: 'S', stock: 16, lowStockThreshold: 5 },
      { size: 'M', stock: 20, lowStockThreshold: 5 },
      { size: 'L', stock: 18, lowStockThreshold: 5 },
      { size: 'XL', stock: 14, lowStockThreshold: 5 },
    ],
    colors: ['beige'],
    materials: ['Linen Blend'],
    sku: 'NXR-W-005',
    tags: ['beige', 'relaxed', 'linen', 'summer'],
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isLimitedDrop: false,
    rating: 4.7,
    reviewCount: 89,
    seoTitle: 'Sand Relaxed Tee | NEXORA Women',
    seoDescription: 'Linen-cotton blend sand t-shirt. Summer essential. Relaxed fit.',
  },

  {
    name: 'Nexora Washed Unisex Tee',
    slug: 'nexora-washed-unisex-tee',
    description: 'A washed unisex essential cut with a soft boxy silhouette. Balanced shoulders, clean neckline, and a refined everyday weight for shared wardrobes.',
    price: 549,
    compareAtPrice: 699,
    category: 'unisex',
    gender: 'unisex',
    collection: 'ivory-atelier',
    images: ['/assets/products/men-cream-tee.jpg'],
    sizes: [
      { size: 'S', stock: 20, lowStockThreshold: 5 },
      { size: 'M', stock: 18, lowStockThreshold: 5 },
      { size: 'L', stock: 16, lowStockThreshold: 5 },
      { size: 'XL', stock: 10, lowStockThreshold: 5 },
    ],
    colors: ['cream'],
    materials: ['Premium Cotton Blend'],
    sku: 'NXR-U-001',
    tags: ['unisex', 'washed', 'essential'],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isLimitedDrop: false,
    rating: 4.9,
    reviewCount: 118,
    seoTitle: 'Nexora Washed Unisex Tee | NEXORA',
    seoDescription: 'Washed unisex essential tee with a premium soft boxy fit.',
  },
  {
    name: 'Essential Unisex Hoodie',
    slug: 'essential-unisex-hoodie',
    description: 'A calm hoodie silhouette with substantial comfort and a clean NEXORA mark. Designed for easy layering and everyday movement.',
    price: 899,
    compareAtPrice: 1099,
    category: 'unisex',
    gender: 'unisex',
    collection: 'ivory-atelier',
    images: ['/assets/products/men-gray-tee.jpg'],
    sizes: [
      { size: 'S', stock: 12, lowStockThreshold: 5 },
      { size: 'M', stock: 14, lowStockThreshold: 5 },
      { size: 'L', stock: 13, lowStockThreshold: 5 },
      { size: 'XL', stock: 9, lowStockThreshold: 5 },
    ],
    colors: ['gray'],
    materials: ['Premium Cotton Blend'],
    sku: 'NXR-U-002',
    tags: ['unisex', 'hoodie', 'essential'],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isLimitedDrop: true,
    rating: 4.8,
    reviewCount: 67,
    seoTitle: 'Essential Unisex Hoodie | NEXORA',
    seoDescription: 'Soft luxury unisex hoodie for everyday comfort.',
  },
];

// Seed reviews
export const SEED_REVIEWS = [
  {
    productId: '', // Will be filled during seeding
    productName: 'Void Oversized Tee',
    customerName: 'Ahmed K.',
    rating: 5,
    title: 'Best t-shirt I have ever owned',
    body: 'The quality is unreal. The fabric is heavy, the fit is perfect, and it has not lost shape after multiple washes. This is what premium feels like.',
    isApproved: true,
    isFeatured: true,
    helpfulCount: 24,
  },
  {
    productId: '',
    productName: 'Ivory Crop Tee',
    customerName: 'Nour S.',
    rating: 5,
    title: 'Perfection in every detail',
    body: 'The crop length is just right, the fabric is incredibly soft, and the cut is so flattering. I have it in two colors now.',
    isApproved: true,
    isFeatured: true,
    helpfulCount: 18,
  },
  {
    productId: '',
    productName: 'Onyx Fitted Tee',
    customerName: 'Maya R.',
    rating: 5,
    title: 'Obsessed with the fit',
    body: 'This tee somehow manages to be both comfortable and incredibly flattering. The bamboo cotton feels amazing against the skin.',
    isApproved: true,
    isFeatured: true,
    helpfulCount: 31,
  },
  {
    productId: '',
    productName: 'Bone Classic Tee',
    customerName: 'Omar H.',
    rating: 4,
    title: 'Great quality, runs slightly large',
    body: 'The Egyptian cotton is noticeably premium. My only note is that it runs a bit large, so consider sizing down if you want a closer fit.',
    isApproved: true,
    isFeatured: false,
    helpfulCount: 12,
  },
  {
    productId: '',
    productName: 'Sage Essential Tee',
    customerName: 'Karim F.',
    rating: 5,
    title: 'The color is everything',
    body: 'The sage green is even better in person. Subtle, sophisticated, and goes with everything. The garment wash gives it that perfect lived-in feel.',
    isApproved: true,
    isFeatured: true,
    helpfulCount: 15,
  },
];
